name: Build Docs
on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "src/**"
      - "README.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        run: python3.11 -m venv .venv

      - name: Install dev dependencies
        run: make install-dev

      - name: Build HTML docs
        run: make docs-html

      - name: Copy diagrams to docs directory
        run: |
          mkdir -p docs/build/html/docs/diagrams
          cp -r docs/diagrams/* docs/build/html/docs/diagrams/

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-site
          path: docs/build/html
          retention-days: 7

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4